version: '3'
services:
  webapp:
    build: .
    container_name: discord-bot
    restart: always
    volumes:
      - ${PWD}/index.js:/usr/src/app/index.js
      - ${PWD}/config.json:/usr/src/app/config.json